### ISSUE TITLE
Error while doing SMBus operation

### ISSUE THREAD

**Issue by Dhina17** [dvlopt/linux-i2c.java#1]
I am facing this exception [0] when I am trying to do SMBus operation in an I2C bus (linux). 
I can't understand why this exception happens. Can you please explain/guess the possibilities why I am facing this issue?
It have no idea while linux ioctl returns error. (Linux IO library).

[0] - https://github.com/helins/linux-i2c.java/blob/140c7259524d394318823a54656f49ba7820c1ce/src/main/java/io/helins/linux/i2c/SMBus.java#L308

**Comment by Dhina17** [comment]
Display wasn't connected correctly. found my issue with error no.

**Comment by helins** [comment]
Glad it works, cheers
